import AppKit

/// A temporary clipboard lease. Restore all original items and representations,
/// but only while we still own the board. Used on the main thread by the app.
final class ClipboardDelivery {
    typealias Snapshot = [[NSPasteboard.PasteboardType: Data]]
    private let board: NSPasteboard
    private let schedule: (TimeInterval, @escaping () -> Void) -> Void
    private var pending: (snapshot: Snapshot, changeCount: Int)?

    init(board: NSPasteboard = .general,
         schedule: @escaping (TimeInterval, @escaping () -> Void) -> Void = { delay, action in
             DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: action)
         }) {
        self.board = board; self.schedule = schedule
    }

    /// Read every representation before changing anything. Lazy/unreadable data
    /// means we cannot preserve this clipboard, so leave it untouched.
    static func snapshot(_ board: NSPasteboard) -> Snapshot? {
        if #available(macOS 15.4, *), board.accessBehavior == .alwaysDeny { return nil }
        let stamp = board.changeCount
        // nil means a read error, not an empty clipboard. Never clear data we
        // couldn't read, including when macOS denies pasteboard access.
        guard let items = board.pasteboardItems else { return nil }
        var result: Snapshot = []
        for item in items {
            var values: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                guard let data = item.data(forType: type) else { return nil }
                values[type] = data
            }
            result.append(values)
        }
        return stamp == board.changeCount ? result : nil
    }

    @discardableResult
    func paste(_ text: String, restoreAfter delay: TimeInterval = 0.8,
               postPaste: () -> Void) -> Bool {
        // A second dictation must preserve the user's clipboard, not the first
        // dictation's temporary text. Old timer callbacks are count-gated below.
        if let pending { restore(changeCount: pending.changeCount) }
        let originalCount = board.changeCount
        guard let original = Self.snapshot(board), originalCount == board.changeCount else { return false }
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
                     "org.nspasteboard.AutoGeneratedType"] {
            item.setData(Data(), forType: .init(type))
        }
        item.setString("com.parla.app", forType: .init("org.nspasteboard.source"))
        board.clearContents()
        guard board.writeObjects([item]) else {
            write(original)
            return false
        }
        let stamp = board.changeCount
        pending = (original, stamp)
        postPaste()
        schedule(delay) { [weak self] in self?.restore(changeCount: stamp) }
        return true
    }

    func restore(changeCount: Int) {
        guard let saved = pending, saved.changeCount == changeCount else { return }
        pending = nil
        guard board.changeCount == changeCount else { return } // keep a new user copy
        write(saved.snapshot)
    }

    private func write(_ snapshot: Snapshot) {
        board.clearContents()
        let items = snapshot.map { representations -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: type) }
            return item
        }
        if !items.isEmpty { board.writeObjects(items) }
    }
}
